### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#27]
1. How can I loop account who has error during example: unfollow

```
                botAccount.Community.unfollowPublisher(profileId, function (err) {
                    if (err)
                        botsManager.errorDebug("Failed to un-follow user. User might already be un-followed. Error: " + err);


----- what I should to put here to loop account until he will do that without error? -----

                    else
                        botsManager.infoDebug("Successfully un-followed user with  " + botAccount.getAccountName());
                });
            })();

```

2. is there a some simple method to keep accounts logged on all the time and do favs/likes or follows without logging them every time with GUI?
 can I just add case in GUIhandler with value of 'node votebot.js' or something?

sorry for stupid questions, my coding skills are at low lvl ^^

**Comment by SamerAlsayegh** [comment]
For question # 1, you simply make it run the code again. You can do this recursively (have it repeat once only because if it fails more that might mean something is wrong, and should be fixed before retrying)
You can do this by enclosing the code in a function and having that function run itsself, if it fails. For example:
```
let functionToRun = function(X, Y, callback){
if (X){
// It failed, so lets re-run the function...
functionToRun(X, Y, callback);
}
else {
// Its all good! No need to rerun function... You can now execute a callback.
callback();
}
}
```
I'd recommend a way to keep track of how many times it ran (maybe pass in counter parameter, which increases on every run, and if it exceeds a certain amount, it completely fails.)


As for question # 2:
If you mean that the session expires, then you can handle that by listening for the 'sessionExpire' event, which returns the account that the session expired for, and just have it login. For example:

```
    botsManager.on('sessionExpired', function (botAccount) {
        botAccount.initUser(function(err){
            botAccount.Auth.loginAccount();
        });
    });
```

This code, however, works with the latest beta version (not full release yet). You can get that version by running 'npm install node-steam-botmanager@beta'. Or you can go through the changes that are on github (github has latest code updates).

**Comment by nextTOPMODEL** [comment]
thank you for advice at #1 question, I will try to implement this

#2 question, I mean I want to run GUIOnly.js (autologin on) then I want to have all accounts logged and doing votebot.js, joinbot.js with GUI like tempList.push("join"); , then I want to do case 'join':, but I don't know what I should to paste in that case.

**Comment by SamerAlsayegh** [comment]
In that case, you will need to honestly look at the code I did, and work from there. It will be a bit of a steep learning curve at first. You can also try to build your own GUI using 'inquirer' library.

**Comment by nextTOPMODEL** [comment]
ok, thank you for advices
