### ISSUE TITLE
Issue with mobile confirmation

### ISSUE THREAD

**Issue by ghost** [Undeadkillz/node-steam-bot-manager#3]
Hey there,
im trying to figure out since over a week now how to setup up successfully the mobile authentification.

When im selecting a bot and using 'Manage' im getting the following output:

```
? Choose the authentication option you would like to activate. [OFF] Two Factor Authentication
Error encountered while trying to enable two-factor-authentication, error code: undefined
```

As next part, how would an automated trading bot would look like, im not that familair yet with nodejs, is it still bound to a gui? Or can i wrote a full application handling automatic trades and so on?

Greetings

Ps: added you on steam, feel free to answere me there for faster interactions.

**Comment by SamerAlsayegh** [comment]
I will check if the issue is from the tool itself or of the issue is from steam servers. But just to make sure, try again incase steam servers were down. 

As for the functionality, the api can be used to build an automated trading bot, just like the one provided in the examples folder. Also yes it runs a console with a GUI but also can handle trades and other functions in the background.

I will add you up asap on Steam, I've just been busy the past few days.

**Comment by SamerAlsayegh** [comment]
Just fixed the issue in the latest commit, just make sure to update the tool by running:
'npm update'.

If you still have an issue, please inform me.
