### ISSUE TITLE
useragent during login

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#30]
Hello, I noticed DoctorKay creator of Steam lib for nodejs started using 

`+const USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36";
+`

in his code for steam-store: https://github.com/DoctorMcKay/node-steamstore/commit/bd9bdde07dbeccfde9a8b0d1a7abb2ab6c375f6f

how can I send this useragent during login to Steam with your script and with every task (like follow etc.)

if I want to add this during login to Steam, should I edit your script or steam-user lib?

Greetings :D

**Comment by SamerAlsayegh** [comment]
Hey! So what you are trying to do, is doable however its not in the npm package yet. So you may stuck with having to clone the repo and running the repo directly (or as a library, if you know how). To specify the user agent, you can do the following:

First however, you will need to disable the auto-login in the config, and handle that yourself, as such:

```
account.initUser(
   {
      request: {
         "headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36";
         }
      }
   }, function(err){
      account.Auth.loginAccount();
   }
);
```
* There is currently no documentation for this code, as it is not fully stable yet, but you may use it and if you encounter issues, just let me know. To have the bots re-login, you will just need to run the 'account.Auth.loginAccount()', instead of all of the code including 'initUser'. The initUser is in case you need to specify a proxy for all the requests to be routed through.


To get the account variable, you can loop through all bots, or find a specific one based on name using findBot.

**Comment by nextTOPMODEL** [comment]
As far I see 'initUser' is added in last 'heavy' update, I don't want to mess with auto-login too, it's too complicated for me, is there any simpler method to edit maybe 'node-steam-user' index.js file? and add there 'User-Agent'?

**Comment by SamerAlsayegh** [comment]
You can instead edit the following [Bot.js](https://github.com/Undeadkillz/node-steam-bot-manager/blob/1bb291549f40ccbb5a0fac4ecb252a2c1a1ab68f/classes/Bot.js#L53)

Replacing it with the following:
```
self.community = new SteamCommunity({
        request: {
         "headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36";
         }
      }
    });
```

Let me know if it works as you expect.. Btw, the Steam-login won't be routed through these settings, as it has its own request settings I believe.

**Comment by nextTOPMODEL** [comment]
getting some error when I replacing:  self.store = new SteamStore();  with this code above.


I think anyway it will be hard to check if it works without some local proxy - like Fiddler?

lately I noticed node-steamcommunity using user-agent too: https://github.com/DoctorMcKay/node-steamcommunity/blob/8e761ffe6c5f7adba457ac09a6e86f3caa4346e1/index.js#L8

so even if I won't edit: 'self.community = new SteamCommunity', do you think my http requests outgoing with:
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36";
from node-steamcommunity code?

like with every follow/like/comment; node-steamcommunity module sending that user-agent by itself?

**Comment by SamerAlsayegh** [comment]
They should be going through that user agent since node-SteamCommunity does that as a default. But as I mentioned earlier, if you want to supply your own user-agent, you will need to pass in your own request into the options of SteamCommunity when it is created. Could you post the error you are getting?

**Comment by nextTOPMODEL** [comment]
to be honest, it is not important function for me, I just asked :D

my code:

```
    self.logger = logger;
    self.community = new SteamCommunity({
        request: {
         "headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36";
         }
      }
    });
    self.client = new SteamUser();
    self.client.logOn();
```

error:
```
\node_modules\node-steam-bot-manager\classes\Bot.js:54
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36";
                                                                                                                                              ^

SyntaxError: Unexpected token ;
```

I removed ';' and script crashing during start

`error: Failed to load "data/accountname.dat" due to {"Error":"Failed to parse due toTypeError: this.request.defaults is not a function"}
Press any key to continue . . .`

**Comment by SamerAlsayegh** [comment]
Hrmm, I think ur Bot.js file needs either updating. Or you need to import requestJs into the Bot.js file and adjust code accordingly.

**Comment by nextTOPMODEL** [comment]
I'm using a bit older version, anyway thank you for your time ;)
