### ISSUE TITLE
features from node-steam-user

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#34]
hello, I just wonder if this is possible to re-write my idler feature to your bot

I have something like this in other nodejs bot

```
	bot.on('accountLimitations', function(limited, communityBanned, locked, canInviteFriends) {
		var limitations = [];
 
		if(limited) {
			limitations.push('LIMITED');
		}
 
		if(communityBanned) {
			limitations.push('COMMUNITY BANNED');
		}
 
		if(locked) {
			limitations.push('LOCKED');
		}
 
		if(limitations.length !== 0) {
			console.log("[" + this.username + "] Limitations: " + limitations.join(', ') + ".");
		}
	});
```

https://github.com/DoctorMcKay/node-steam-user#accountlimitations
is it possible to use it with your code?

should I use something like this?

`botsManager.on('accountLimitations', function (botAccount) {`

I think is doesn't work

**Comment by SamerAlsayegh** [comment]
You can actually hook to the native methods in DoctorMcKay's library. The only issue is you will need to do this for every bot you initialize, since that event hook is not included in node-steam-bot-manager natively.

1. Hook to the loggedIn event to get the botAccount that loggedin.
2. Access the botAccount's 'client' object (so using botAccount.client)

3. You can now either access the 'limitations' property if its set or hook to the events of 'accountLimitations' by using:

```
botAccount.client.on('accountLimitations', function(limited, communityBanned, locked, canInviteFriends) {
		var limitations = [];
 
		if(limited) {
			limitations.push('LIMITED');
		}
 
		if(communityBanned) {
			limitations.push('COMMUNITY BANNED');
		}
 
		if(locked) {
			limitations.push('LOCKED');
		}
 
		if(limitations.length !== 0) {
			console.log("[" + this.username + "] Limitations: " + limitations.join(', ') + ".");
		}
	}));
```

My bad on the late response didn't get an email for this issue request.

**Comment by xc4t** [comment]
hmm, I think it's too complicated for me :/

something like this, or I'm totally wrong?

```
function limit() {

    botsManager.on('loggedIn', function (botAccount) {

	botAccount.client.on('accountLimitations', function(limited, communityBanned, locked, canInviteFriends) {
		var limitations = [];
 
		if(limited) {
			limitations.push('LIMITED');
		}
 
		if(communityBanned) {
			limitations.push('COMMUNITY BANNED');
		}
 
		if(locked) {
			limitations.push('LOCKED');
		}
 
		if(limitations.length !== 0) {
			console.log("[" + this.username + "] Limitations: " + limitations.join(', ') + ".");
		}
	});
	
});
    botsManager.startManager(function (err) {
    });
}
```

**Comment by SamerAlsayegh** [comment]
Yeah I believe that is it. If that even does not run, it might mean that the accountLimitations events already ran, so a better way would be to check the properties of the client, since the properties should already be set. It will need a bit of testing, to verify. I won't be able to reproduce it and help out as I don't have access to my testing pc at this time.

**Comment by nextTOPMODEL** [comment]
Yes, please test it in free time, I have no idea how to do it :D
