### ISSUE TITLE
oAuthToken

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#40]
Hello, looks like oAuthToken expiring after 1 year (365 days) after add.
is there any method to prevent it?

I need to re-add accounts, because getting 401 error exactly after 1 year after add account.

**Comment by SamerAlsayegh** [comment]
As far as I know, you will need to re-run the login function with the password. So one way to trigger that is to ensure each data file has a 'password' property and no 'oAuthToken' property, before you run the tool. 

Since I didn't really handle this error in the tool (my bad, didn't expect it), you may have to manually delete that property (or write a script to do so, if you have a lot of accounts).

**Comment by xc4t** [comment]
Thank you for informations, so I will do it like before: I deleting .dat file (with account info) and re-adding it.
