### ISSUE TITLE
CLOSED.

### ISSUE THREAD

**Issue by xc4t** [Undeadkillz/node-steam-bot-manager#42]
CLOSED.

**Comment by nextTOPMODEL** [comment]
oh RIP probably, because password isn't stored in .dat file

**Comment by nextTOPMODEL** [comment]
I was thinking about it and I have some idea: in Auth class I can add:

if (err.code == 401) - then read my .txt file with my accounts, I have login:pass format (because saved .dat file doesn't contain password if oAuth is present), I can push my accounts from .txt file to array, then check the array if contain: self.accountName, if yes, I can grab password from my array

then I can try to log account with self.accountName, and password from array
but how can I do it? self.loginAccount?

and when it will prompt about steam guard I can add some imap reader

**Comment by SamerAlsayegh** [comment]
Well to do a mailbox read is a whole other program on it's own tbh. So what I would recommend is just building a script that strips out the oauth token from the account data files. Aslong as the password is saved in the data file, it should be able to recreate new tokens right away with no problems.

I will have to fix this issue when I get the time. However lately my dev has been limited on this project.

**Comment by xc4t** [comment]
sure, no problem, I just creating new dat files, and replacing them, no big deal :p
