### ISSUE TITLE
TypeError: Cannot read property 'createOffer' of undefined

### ISSUE THREAD

**Issue by dihmeetree** [Undeadkillz/node-steam-bot-manager#8]
Getting the following error! 

botAccount.TradeManager.createOffer(partnerSid, function (err, currentOffer) {

TypeError: Cannot read property 'createOffer' of undefined
    at C:\Users\LolCoolKat\Documents\node-steam-bot-manager\APITradeBot.js:80:52

Any help would be appreciated!

**Comment by SamerAlsayegh** [comment]
The issue should be fixed, please refer to latest update/commit.
Simply type 'npm update' in the console while in the project folder, and also download the new example file, located [here](https://raw.githubusercontent.com/Undeadkillz/node-steam-bot-manager/master/examples/APITradeBot.js). 

I will leave the Issue open for the next few days, incase you have another issue regarding this functionality. Otherwise you may close it if the issue is resolved.

**Comment by dihmeetree** [comment]
Thank you! I am all set for the time being.
